---
title: "NW bromii"
output: html_notebook
---

```{r}
library(data.table)
library(dplyr)
library(magrittr)
```
```{r}
setwd('/shares/CIBIO-Storage/CM/scratch/users/francesco.beghini/chocophlan_paper/')
```

```{bash}
cat /shares/CIBIO-Storage/CM/scratch/users/leonard.dubois/rbromii4000_panphlan/cluster1.tree | tr ',' '\n' | tr -d '('| tr -d ')' | tr -d "'" | cut -f1 -d ':' > /tmp/cluster2
cat /shares/CIBIO-Storage/CM/scratch/users/leonard.dubois/rbromii4000_panphlan/cluster2.tree | tr ',' '\n' | tr -d '('| tr -d ')' | tr -d "'" | cut -f1 -d ':' > /tmp/cluster1
```



```{r}
panphlan_table <- fread('/shares/CIBIO-Storage/CM/scratch/users/leonard.dubois/rbromii4000_panphlan/profile_4000_rbromii.csv')
metadata <- fread('/shares/CIBIO-Storage/CM/scratch/users/leonard.dubois/rbromii4000_panphlan/metadata_eu.csv')
metadata$sampleID <- sapply(strsplit(metadata$sampleID, '__'), `[`,2)

cluster2_samples <- fread('/tmp/cluster2', col.names = c('sampleID'))
cluster2_samples$sampleID <- sapply(strsplit(cluster2_samples$sampleID, '__'), `[`,2)
cluster2_samples <- cluster2_samples[, cluster := '2']
cluster1_samples <- fread('/tmp/cluster1', col.names = c('sampleID'))
cluster1_samples$sampleID <- sapply(strsplit(cluster1_samples$sampleID, '__'), `[`,2)
cluster1_samples <- cluster1_samples[, cluster := '1']

```

```{r}
t_panphlan_table <- data.table::transpose(panphlan_table)
colnames(t_panphlan_table) <- as.character(t_panphlan_table[1,] )
t_panphlan_table <- t_panphlan_table[-1,]
t_panphlan_table <- cbind(sample=t(colnames(panphlan_table))[-1], t_panphlan_table)
t_panphlan_table$sample <- gsub('_map.tsv.bz2', '', t_panphlan_table$sample)
```


<!-- ## Westernization -->
<!-- ```{r} -->
<!-- phpa_merged <- merge(t_panphlan_table, metadata[,-2], by.x ='sample', by.y = 'sampleID') -->
<!-- sample_names <- phpa_merged$sample -->
<!-- westernised <- phpa_merged$westernised -->
<!-- phpa_merged <- phpa_merged[,-1][, lapply(.SD, as.numeric), .SDcols = !c('westernised')] -->
<!-- phpa_merged <- phpa_merged[, westernised := westernised] -->
<!-- x <- phpa_merged[, lapply(.SD, sum), by=westernised] -->
<!-- tx <- data.table(t(x[,-1])) -->
<!-- colnames(tx) <- x$westernised -->
<!-- ``` -->

<!-- ```{r} -->
<!-- total_w <- table(westernised)[['W']] -->
<!-- total_nw <- table(westernised)[['NW']] -->
<!-- ``` -->

<!-- ```{r} -->
<!-- tx <- tx[, `:=`(W_A=total_w-W, NW_A=total_nw-NW) ] -->

<!-- contingency <- function(r){ -->
<!--   mat <- matrix(rev(as.numeric(r)), ncol = 2, dimnames = list(c('NW','W'),c('N','Y'))) -->
<!--   tmp <- fisher.test(mat) -->
<!--   p <- tmp$p.value -->
<!--   or <- (mat[1,2]/mat[1,1]) / (mat[2,2]/mat[2,1]) -->

<!--   return(c('pvalue'=p, 'OR'=or)) -->
<!-- } -->

<!-- ax <- data.table(colnames(phpa_merged)[-6152], t(apply(tx, 1, contingency))) -->
<!-- ax <- cbind(ax, tx) -->
<!-- ax <- ax[pvalue<0.05 & OR>1] -->
<!-- ``` -->



## Cluster 2

```{r}
phpa_merged_cluster2 <- merge(t_panphlan_table, cluster2_samples, by.x ='sample', by.y = 'sampleID', all.x = TRUE)
sample_names <- phpa_merged_cluster2$sample
cluster <- phpa_merged_cluster2$cluster
cluster[is.na(cluster)] <- 'other'

phpa_merged_cluster2 <- phpa_merged_cluster2[,-1][, lapply(.SD, as.numeric), .SDcols = !c('cluster')]
phpa_merged_cluster2 <- phpa_merged_cluster2[, cluster := cluster]
x <- phpa_merged_cluster2[, lapply(.SD, sum), by=cluster]
tx <- data.table(t(x[,-1]))
colnames(tx) <- c('other','cl2')
```

```{r}
total_2 <- table(cluster)[[1]]
total_other <- table(cluster)[[2]]
```

```{r}
tx <- tx[, `:=`(cl2_A=total_2-cl2, other_A=total_other-other) ]
tx <- tx[,c(2,1,3,4)]

contingency <- function(r){
  mat <- matrix(as.numeric(r), ncol = 2, dimnames = list(c('2','other'),c('Y','N')))
  tmp <- fisher.test(mat)
  p <- tmp$p.value
  # or <- (mat[1,2]/mat[1,1]) / (mat[2,2]/mat[2,1])
  or <- tmp$estimate[[1]]
  
  return(c('pvalue'=p, 'OR'=or))
}

ax <- data.table(colnames(phpa_merged_cluster2)[-6152], t(apply(tx, 1, contingency)))
ax <- cbind(ax, tx)
# ax <- ax[pvalue<0.05 & OR>1]
write.table(ax, 'rbromii_clust2_ass.tsv', row.names = FALSE, quote = FALSE, sep = '\t')
```

```{r}
filt_pangenome <- c[V1 %in% ax$V1,.(geneName = paste(list(V2), collapse = ',')), by= V1]
write.table(filt_pangenome, 'rbromii_clust2_ass_genenames', row.names = FALSE, quote = FALSE, sep = '\t')
```

## Cluster 1

```{r}
phpa_merged_cluster1 <- merge(t_panphlan_table, cluster1_samples, by.x ='sample', by.y = 'sampleID', all.x = TRUE)
sample_names1 <- phpa_merged_cluster1$sample
cluster1 <- phpa_merged_cluster1$cluster
cluster1[is.na(cluster1)] <- 'other'

phpa_merged_cluster1 <- phpa_merged_cluster1[,-1][, lapply(.SD, as.numeric), .SDcols = !c('cluster')]
phpa_merged_cluster1 <- phpa_merged_cluster1[, cluster := cluster1]
x <- phpa_merged_cluster1[, lapply(.SD, sum), by=cluster]
tx <- data.table(t(x[,-1]))
colnames(tx) <- c('other','cl1')
```

```{r}
total_1 <- table(cluster1)[[1]]
total_other <- table(cluster1)[[2]]
```

```{r}
tx <- tx[, `:=`(cl1_A=total_1-cl1, other_A=total_other-other) ]
tx <- tx[,c(2,1,3,4)]

contingency <- function(r){
  mat <- matrix(as.numeric(r), ncol = 2, dimnames = list(c('1','other'),c('Y','N')))
  tmp <- fisher.test(mat)
  p <- tmp$p.value
  # or <- (mat[1,2]/mat[1,1]) / (mat[2,2]/mat[2,1])
  or <- tmp$estimate[[1]]
  
  return(c('pvalue'=p, 'OR'=or))
}

ax <- data.table(colnames(phpa_merged_cluster1)[-6152], t(apply(tx, 1, contingency)))
ax <- cbind(ax, tx)
ax <- ax[pvalue<0.05 & OR>1]
write.table(ax, 'rbromii_clust1_ass.tsv', row.names = FALSE, quote = FALSE, sep = '\t')
```

## Cluster 1 enriched for Chinese samples
```{r}
merged_cluster1 <- merge(metadata, cluster1_samples, by.x ='sampleID', by.y = 'sampleID', all.x = TRUE)
merged_cluster1 <- merged_cluster1[subjectID != 'REF']
merged_cluster1$cluster[is.na(merged_cluster1$cluster)] <- 'other'

ch1 <- nrow(merged_cluster1[subjectID == 'CHN' & cluster == 1])
cho <- nrow(merged_cluster1[subjectID == 'CHN' & cluster != 1])
al1 <- nrow(merged_cluster1[subjectID != 'CHN' & cluster == 1])
alo <- nrow(merged_cluster1[subjectID != 'CHN' & cluster != 1])

mat <- matrix(c(ch1, cho, al1, alo), ncol = 2, byrow = TRUE, dimnames = list(c('1','other'),c('CHN','OTH')))
tmp <- fisher.test(mat)
p <- tmp$p.value
# or <- (mat[1,2]/mat[1,1]) / (mat[2,2]/mat[2,1])
or <- tmp$estimate[[1]]
```




## To NR50
```{r}
# rbromii_annot <- fread('/shares/CIBIO-Storage/CM/scratch/users/francesco.beghini/hg/chocophlan/export_201901/humann2/HUMAnN_3.0_CHOCOPhlAn_201901_functional_annotation_mapping.tsv', sep = '\t', nThread = 12)
# c <- fread('/shares/CIBIO-Storage/CM/scratch/users/leonard.dubois/PanPhlAn_work/old_pangenomes/panphlan_rbromii_pangenome.csv', nThread = 12)

clusters <- data.frame(sample_names, cluster)
clusters <- unique(clusters)
rownames(clusters) <- clusters$sample_names

# rbromii_annot_filt <- rbromii_annot[rbromii_annot$V1 %in% c$V1,]
rbromii_annot_filt <- fread('rbromii_func_annot.tsv')

aaa <- merge(rbromii_annot_filt[,c(1,2)],panphlan_table, by.y = 'V1', by.x = 'V1', all.y = TRUE)[,-1]
sample_names <- colnames(aaa)[-1]
sample_names <- gsub('_map.tsv.bz2', '', sample_names)

aaa <- transpose(aaa[, lapply(.SD, sum), by=V2])
colnames(aaa) <- as.character(aaa[1,])
aaa <- data.table(aaa)[-1,][, lapply(.SD, as.numeric)]
aaa[aaa>1] <- 1
aaa <- cbind(cluster = clusters[sample_names,'cluster'], aaa)
# aaa <- cbind(sampleID = sample_names, aaa)

NR50 <- aaa[, lapply(.SD, sum), by=cluster]
NR50 <- data.table(t(NR50[,-1]))
colnames(NR50) <- c('other','cl2')
NR50 <- NR50[, `:=`(cl2_A=total_2-cl2, other_A=total_other-other) ]
NR50 <- NR50[,c(2,1,3,4)]

contingency <- function(r){
  mat <- matrix(as.numeric(r), ncol = 2, dimnames = list(c('2','other'),c('Y','N')))
  tmp <- fisher.test(mat)
  p <- tmp$p.value
  # or <- (mat[1,2]/mat[1,1]) / (mat[2,2]/mat[2,1])
  or <- tmp$estimate[[1]]
  
  return(c('pvalue'=p, 'OR'=or))
}

ax <- data.table(colnames(aaa)[-1], t(apply(NR50, 1, contingency)))
ax <- cbind(ax, NR50)
ax <- ax[pvalue<0.05 & OR>1]
write.table(ax, 'rbromii_clust2_ass_NR50.tsv', row.names = FALSE, quote = FALSE, sep = '\t')
```

```{r}
NR50names <- fread('/shares/CIBIO-Storage/CM/scratch/users/francesco.beghini/chocophlan_paper/cluster2_enrich_names', col.names = c('NR50','descr'))
mergedax <- merge(ax, NR50names, by.x='V1', by.y ='NR50')
```
